# Generated by Django 5.2.3 on 2026-01-25 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0001_initial'),
        ('core', '0001_initial'),
        ('receivables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receivables.payment'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='payment_reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receivables.paymentreminder'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='core.school'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='core.student'),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_templates', to='core.school'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.communicationtemplate'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receivables.payment'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='payment_reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receivables.paymentreminder'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='core.school'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='core.student'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.communicationtemplate'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='email_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.emailmessage'),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receivables.payment'),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='payment_reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receivables.paymentreminder'),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='core.school'),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='core.student'),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.communicationtemplate'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='sms_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.smsmessage'),
        ),
        migrations.AlterUniqueTogether(
            name='communicationtemplate',
            unique_together={('school', 'name', 'message_type', 'template_type')},
        ),
        migrations.AlterUniqueTogether(
            name='emailmessage',
            unique_together={('school', 'recipient_email', 'subject', 'created_at')},
        ),
        migrations.AlterUniqueTogether(
            name='smsmessage',
            unique_together={('school', 'recipient_phone', 'content', 'created_at')},
        ),
        migrations.AlterUniqueTogether(
            name='communicationlog',
            unique_together={('school', 'student', 'communication_type', 'created_at')},
        ),
    ]
