# Generated by Django 5.2.3 on 2026-01-26 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_initial'),
        ('core', '0002_initial'),
        ('receivables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['school', 'student', 'communication_type', 'created_at'], name='comm_log_sch_stu_typ_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['school', 'communication_type', 'created_at'], name='comm_log_sch_typ_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['student', 'created_at'], name='comm_log_stu_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['school', 'student', 'status', 'created_at'], name='email_msg_sch_stu_st_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['school', 'status', 'created_at'], name='email_msg_sch_st_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['student', 'status'], name='email_msg_stu_st_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['status', 'created_at'], name='email_msg_st_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['school', 'student', 'status', 'created_at'], name='sms_msg_sch_stu_st_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['school', 'status', 'created_at'], name='sms_msg_sch_st_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['student', 'status'], name='sms_msg_stu_st_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['status', 'created_at'], name='sms_msg_st_crt_idx'),
        ),
    ]
