# Generated by Django 5.2.3 on 2026-01-03 20:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "2023-2024"', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False, help_text='Whether this academic year is currently active')),
                ('is_current', models.BooleanField(default=False, help_text='The current academic year (only one can be current)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('tuition', 'Tuition'), ('transport', 'Transport'), ('meals', 'Meals'), ('activities', 'Activities'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_optional', models.BooleanField(default=False, help_text='If checked, this fee is optional and students can opt in/out')),
                ('apply_by_default', models.BooleanField(default=False, help_text='If checked, optional fees will be selected by default when adding/editing students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fee Categories',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "A", "B", "Morning", "Afternoon"', max_length=50)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of students (optional)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['school_class__grade__name', 'school_class__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('upi', models.CharField(blank=True, help_text='11-digit NEMIS / UPI number issued by the Ministry of Education', max_length=11, null=True, unique=True, verbose_name='NEMIS/UPI Number')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, help_text='Middle or other names (optional)', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('admission_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_phone', models.CharField(max_length=15)),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('uses_transport', models.BooleanField(default=False)),
                ('pays_meals', models.BooleanField(default=True)),
                ('pays_activities', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, help_text='Student photo', null=True, upload_to='student_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['grade', 'first_name', 'middle_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.PositiveIntegerField(blank=True, help_text='Roll number in class', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retained', 'Retained'), ('promoted', 'Promoted'), ('graduated', 'Graduated'), ('left', 'Left School'), ('dropped', 'Dropped Out')], default='active', max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this enrollment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Class Enrollment',
                'verbose_name_plural': 'Student Class Enrollments',
                'ordering': ['roll_number', 'student__first_name', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['student', 'term', 'fee_category'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('term_number', models.CharField(choices=[('1', 'First Term'), ('2', 'Second Term'), ('3', 'Third Term')], max_length=1)),
                ('academic_year', models.CharField(max_length=9)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-academic_year', 'term_number'],
            },
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('active_start_date', models.DateField(blank=True, help_text='Start date when this route becomes active', null=True)),
                ('active_end_date', models.DateField(blank=True, help_text='End date when this route becomes inactive', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='Deprecated: Use roles instead', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('preferred_contact_method', models.CharField(choices=[('phone', 'Phone'), ('sms', 'SMS'), ('email', 'Email')], default='phone', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ParentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], max_length=20)),
                ('verification_code', models.CharField(max_length=10)),
                ('new_value', models.CharField(help_text='New phone number or email address', max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='core.parent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('view', 'View'), ('add', 'Add'), ('change', 'Change'), ('delete', 'Delete')], max_length=20)),
                ('resource_type', models.CharField(choices=[('student', 'Student'), ('grade', 'Grade'), ('term', 'Term'), ('class', 'Class'), ('fee_structure', 'Fee Structure'), ('fee', 'Fee'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('reminder', 'Reminder'), ('attendance', 'Attendance'), ('subject', 'Subject'), ('teacher', 'Teacher'), ('timetable', 'Timetable'), ('exam', 'Exam'), ('gradebook', 'Gradebook'), ('assignment', 'Assignment'), ('submission', 'Submission'), ('template', 'Template'), ('email', 'Email'), ('sms', 'SMS'), ('log', 'Communication Log'), ('dashboard', 'Dashboard'), ('report', 'Report'), ('user_management', 'User Management'), ('role_management', 'Role Management'), ('school_management', 'School Management')], max_length=30)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['resource_type', 'permission_type'],
                'unique_together': {('permission_type', 'resource_type')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('super_admin', 'Super Admin'), ('school_admin', 'School Admin'), ('teacher', 'Teacher'), ('accountant', 'Accountant'), ('parent', 'Parent'), ('student', 'Student')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this role')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='core.permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('primary_color', models.CharField(default='#0d6efd', help_text='Primary color for the school theme (hex code)', max_length=7)),
                ('secondary_color', models.CharField(blank=True, help_text='Secondary color for the school theme (hex code)', max_length=7, null=True)),
                ('use_color_scheme', models.BooleanField(default=False, help_text='Apply this color scheme to the application')),
                ('use_secondary_on_headers', models.BooleanField(default=False, help_text='Apply secondary color to headers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_school_name'), models.UniqueConstraint(fields=('email',), name='unique_school_email')],
            },
        ),
        migrations.CreateModel(
            name='PromotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('bulk', 'Bulk')], default='automatic', max_length=20)),
                ('total_students', models.PositiveIntegerField(help_text='Total students processed')),
                ('promoted_count', models.PositiveIntegerField(default=0)),
                ('retained_count', models.PositiveIntegerField(default=0)),
                ('graduated_count', models.PositiveIntegerField(default=0)),
                ('left_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this promotion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='core.academicyear')),
                ('promoted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to=settings.AUTH_USER_MODEL)),
                ('to_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='core.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_logs', to='core.school')),
            ],
            options={
                'verbose_name': 'Promotion Log',
                'verbose_name_plural': 'Promotion Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='parent',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='core.school'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='core.feecategory')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='core.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='core.school')),
            ],
            options={
                'ordering': ['grade', 'term', 'fee_category'],
            },
        ),
        migrations.AddField(
            model_name='feecategory',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_categories', to='core.school'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='core.school'),
        ),
    ]
