# Generated by Django 5.2.3 on 2025-12-30 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='Assigned class teacher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_taught', to='timetable.teacher'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_classes', to='core.grade'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_classes', to='core.school'),
        ),
        migrations.AddField(
            model_name='section',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.school'),
        ),
        migrations.AddField(
            model_name='section',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.schoolclass'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.grade'),
        ),
        migrations.AddField(
            model_name='student',
            name='optional_fee_categories',
            field=models.ManyToManyField(blank=True, help_text='Optional fee categories this student has opted into', related_name='students_opted_in', to='core.feecategory'),
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, help_text='Linked parent user accounts', related_name='children', to='core.parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(blank=True, help_text='Assigned class (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.schoolclass'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to student user account (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentclassenrollment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='studentclassenrollment',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.grade'),
        ),
        migrations.AddField(
            model_name='studentclassenrollment',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='core.schoolclass'),
        ),
        migrations.AddField(
            model_name='studentclassenrollment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='core.section'),
        ),
        migrations.AddField(
            model_name='studentclassenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='core.feecategory'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='core.school'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='core.student'),
        ),
        migrations.AddField(
            model_name='term',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.school'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='core.term'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='core.term'),
        ),
        migrations.AddField(
            model_name='transportroute',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='core.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.transportroute'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='core.role'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.school'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='parent',
            unique_together={('school', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='feecategory',
            unique_together={('school', 'name', 'category_type')},
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('school', 'grade', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('school_class', 'name')},
        ),
        migrations.AddIndex(
            model_name='studentclassenrollment',
            index=models.Index(fields=['academic_year', 'status'], name='core_studen_academi_e5c0af_idx'),
        ),
        migrations.AddIndex(
            model_name='studentclassenrollment',
            index=models.Index(fields=['grade', 'academic_year'], name='core_studen_grade_i_e842f1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentclassenrollment',
            index=models.Index(fields=['school_class', 'section'], name='core_studen_school__d667fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentclassenrollment',
            unique_together={('student', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('school', 'term_number', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='studentfee',
            unique_together={('school', 'student', 'term', 'fee_category')},
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('school', 'grade', 'term', 'fee_category')},
        ),
        migrations.AlterUniqueTogether(
            name='transportroute',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'student_id')},
        ),
    ]
