# Generated by Django 5.2.3 on 2026-01-26 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['school', 'is_active'], name='academicyear_school_active_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['school', 'is_current'], name='acad_year_sch_curr_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['is_active', 'is_current'], name='acad_year_act_curr_idx'),
        ),
        migrations.AddIndex(
            model_name='feecategory',
            index=models.Index(fields=['school', 'category_type'], name='feecategory_school_type_idx'),
        ),
        migrations.AddIndex(
            model_name='feecategorytype',
            index=models.Index(fields=['school', 'is_active'], name='fee_cat_type_sch_act_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['school', 'grade', 'term'], name='fee_struct_sch_gr_term_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['school', 'is_active'], name='fee_struct_sch_act_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['grade', 'term', 'is_active'], name='fee_struct_gr_term_act_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['school'], name='grade_school_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['school', 'is_active'], name='parent_school_active_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['user'], name='parent_user_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionlog',
            index=models.Index(fields=['school', 'created_at'], name='promo_log_sch_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionlog',
            index=models.Index(fields=['from_academic_year', 'to_academic_year'], name='promotionlog_years_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['school', 'is_active'], name='role_school_active_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name', 'is_active'], name='role_name_active_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolclass',
            index=models.Index(fields=['school', 'grade', 'is_active'], name='school_cls_sch_gr_act_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolclass',
            index=models.Index(fields=['school', 'is_active'], name='schoolclass_school_active_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolclass',
            index=models.Index(fields=['grade', 'is_active'], name='schoolclass_grade_active_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['school_class', 'is_active'], name='section_class_active_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['school', 'is_active'], name='section_school_active_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'is_active'], name='student_school_active_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'grade', 'is_active'], name='stud_sch_gr_act_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'school_class', 'is_active'], name='stud_sch_cls_act_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='student_id_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['upi'], name='student_upi_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['grade', 'is_active'], name='student_grade_active_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['school', 'student', 'term'], name='stud_fee_sch_stu_term_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['school', 'student', 'is_paid'], name='stud_fee_sch_stu_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['school', 'due_date', 'is_paid'], name='stud_fee_sch_due_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['student', 'term', 'is_paid'], name='stud_fee_stu_term_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['due_date'], name='student_fee_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['school', 'is_active'], name='term_school_active_idx'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['school', 'academic_year', 'is_active'], name='term_school_year_active_idx'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['academic_year', 'is_active'], name='term_year_active_idx'),
        ),
        migrations.AddIndex(
            model_name='transportroute',
            index=models.Index(fields=['school', 'is_active'], name='trans_route_sch_act_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='userprofile_user_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['school', 'is_active'], name='userprofile_school_active_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user', 'school'], name='userprofile_user_school_idx'),
        ),
    ]
