# Generated by Django 5.2.3 on 2026-01-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='photo',
            field=models.ImageField(blank=True, help_text='Parent photo', null=True, upload_to='parent_photos/'),
        ),
    ]
