# Generated by Django 5.2.3 on 2026-01-27

from decimal import Decimal
from django.db import migrations


def clamp_negative_amount_paid(apps, schema_editor):
    """Fix any StudentFee with amount_paid < 0 (e.g. after reversal > allocated or credits deleted)."""
    StudentFee = apps.get_model('core', 'StudentFee')
    for fee in StudentFee.objects.filter(amount_paid__lt=0):
        fee.amount_paid = Decimal('0')
        fee.is_paid = False
        fee.save(update_fields=['amount_paid', 'is_paid'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RunPython(clamp_negative_amount_paid, noop),
    ]
