# Generated by Django 5.2.3 on 2026-01-06 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_parent_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feecategory',
            options={'verbose_name_plural': 'Fee Categories'},
        ),
        migrations.CreateModel(
            name='FeeCategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the fee category type (e.g., Tuition, Transport)', max_length=100)),
                ('code', models.CharField(help_text='Short code for the type (e.g., tuition, transport)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description for this category type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category type is active and can be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_category_types', to='core.school')),
            ],
            options={
                'verbose_name': 'Fee Category Type',
                'verbose_name_plural': 'Fee Category Types',
                'ordering': ['name'],
                'unique_together': {('school', 'code')},
            },
        ),
        # Add temporary field to store the ForeignKey
        migrations.AddField(
            model_name='feecategory',
            name='category_type_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_categories_new', to='core.feecategorytype'),
        ),
    ]
