# Generated by Django 5.2.3

from django.db import migrations

# Old category choices mapping
CATEGORY_CHOICES_MAP = {
    'tuition': {'name': 'Tuition', 'description': 'Tuition fees'},
    'transport': {'name': 'Transport', 'description': 'Transportation fees'},
    'meals': {'name': 'Meals', 'description': 'Meal fees'},
    'activities': {'name': 'Activities', 'description': 'Activity fees'},
    'other': {'name': 'Other', 'description': 'Other fees'},
}


def create_category_types_and_migrate_data(apps, schema_editor):
    """Create FeeCategoryType objects and migrate existing FeeCategory data"""
    FeeCategoryType = apps.get_model('core', 'FeeCategoryType')
    FeeCategory = apps.get_model('core', 'FeeCategory')
    School = apps.get_model('core', 'School')
    
    # Get all schools
    schools = School.objects.all()
    
    # Create category types for each school
    for school in schools:
        for code, data in CATEGORY_CHOICES_MAP.items():
            # Check if type already exists (in case migration is run multiple times)
            fee_category_type, created = FeeCategoryType.objects.get_or_create(
                school=school,
                code=code,
                defaults={
                    'name': data['name'],
                    'description': data['description'],
                    'is_active': True,
                }
            )
    
    # Migrate existing FeeCategory records
    for fee_category in FeeCategory.objects.all():
        if fee_category.category_type:  # If it's still a string
            try:
                # Find the corresponding FeeCategoryType
                category_type = FeeCategoryType.objects.get(
                    school=fee_category.school,
                    code=fee_category.category_type
                )
                # Set the new ForeignKey field
                fee_category.category_type_new = category_type
                fee_category.save()
            except FeeCategoryType.DoesNotExist:
                # If type doesn't exist, create it
                code = fee_category.category_type
                data = CATEGORY_CHOICES_MAP.get(code, {'name': code.title(), 'description': ''})
                category_type = FeeCategoryType.objects.create(
                    school=fee_category.school,
                    code=code,
                    name=data['name'],
                    description=data['description'],
                    is_active=True,
                )
                fee_category.category_type_new = category_type
                fee_category.save()


def reverse_migration(apps, schema_editor):
    """Reverse migration - convert back to string values"""
    FeeCategory = apps.get_model('core', 'FeeCategory')
    
    # Convert ForeignKey back to string
    for fee_category in FeeCategory.objects.all():
        if fee_category.category_type_new:
            fee_category.category_type = fee_category.category_type_new.code
            fee_category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_feecategory_options_feecategorytype_and_more'),
    ]

    operations = [
        migrations.RunPython(create_category_types_and_migrate_data, reverse_migration),
    ]
