# Generated by Django 5.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clamp_negative_studentfee_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecategory',
            name='allocation_order',
            field=models.PositiveIntegerField(
                default=999,
                help_text='Order when splitting payments across receivables: lower numbers are allocated first (e.g. 1=Tuition, 2=Transport, 3=Diary).'
            ),
        ),
    ]
