# Generated by Django 5.2.3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_migrate_category_types'),
    ]

    operations = [
        # Remove the old CharField
        migrations.RemoveField(
            model_name='feecategory',
            name='category_type',
        ),
        # Rename the new field to the original name
        migrations.RenameField(
            model_name='feecategory',
            old_name='category_type_new',
            new_name='category_type',
        ),
        # Update the field to ensure proper ForeignKey constraints
        migrations.AlterField(
            model_name='feecategory',
            name='category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_categories', to='core.feecategorytype'),
        ),
        # Update Meta options with new ordering
        migrations.AlterModelOptions(
            name='feecategory',
            options={'ordering': ['category_type__name', 'name'], 'verbose_name_plural': 'Fee Categories'},
        ),
    ]
