# Generated by Django 5.2.3 on 2026-01-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_finalize_category_type_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short name for school (used in usernames). Format: one word or two words separated by dot, comma, or hyphen. No spaces or special characters allowed. Example: "ambassador" or "hip.hop" or "school-name"', max_length=50, null=True, unique=True),
        ),
    ]
