# Generated by Django 5.2.3 on 2025-11-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_create_schoolclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text='Student photo', null=True, upload_to='student_photos/'),
        ),
    ]
