# Generated by Django 5.2.3 on 2026-01-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_school_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short name for school (used in usernames). Format: one word or two words separated by dot (.), ampersand (&), or hyphen (-). No spaces or other special characters allowed. Example: "ambassador" or "hip.hop" or "school-name" or "amb&assad". Required for creating parent users.', max_length=50, null=True, unique=True),
        ),
    ]
