# Generated by Django 5.2.3 on 2026-01-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_school_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='display_name',
            field=models.CharField(blank=True, help_text='Human-readable display name (e.g., "Librarian", "Security Guard"). If left blank, will be auto-generated from name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Role name (use lowercase with underscores, e.g., "librarian", "security_guard")', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short name for school (used in usernames). Format: one word or two words separated by dot (.), underscore (_), or hyphen (-). No spaces or other special characters allowed. Example: "ambassador" or "hip.hop" or "school-name" or "amb_assad". Required for creating parent users.', max_length=50, null=True, unique=True),
        ),
    ]
