# Generated by Django 5.2.3 on 2026-01-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_custom_roles_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='resource_type',
            field=models.CharField(choices=[('student', 'Student'), ('grade', 'Grade'), ('term', 'Term'), ('class', 'Class'), ('fee_structure', 'Fee Structure'), ('fee', 'Fee'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('reminder', 'Reminder'), ('attendance', 'Attendance'), ('subject', 'Subject'), ('teacher', 'Teacher'), ('timetable', 'Timetable'), ('exam', 'Exam'), ('gradebook', 'Gradebook'), ('assignment', 'Assignment'), ('submission', 'Submission'), ('template', 'Template'), ('email', 'Email'), ('sms', 'SMS'), ('log', 'Communication Log'), ('dashboard', 'Dashboard'), ('report', 'Report'), ('user_management', 'User Management'), ('role_management', 'Role Management'), ('school_management', 'School Management'), ('parent_portal', 'Parent Portal')], max_length=30),
        ),
    ]
