# Generated by Django 5.2.3 on 2025-11-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, help_text='Deprecated: Use roles instead', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('view', 'View'), ('add', 'Add'), ('change', 'Change'), ('delete', 'Delete')], max_length=20)),
                ('resource_type', models.CharField(choices=[('student', 'Student'), ('grade', 'Grade'), ('term', 'Term'), ('class', 'Class'), ('fee_structure', 'Fee Structure'), ('fee', 'Fee'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('reminder', 'Reminder'), ('attendance', 'Attendance'), ('subject', 'Subject'), ('teacher', 'Teacher'), ('timetable', 'Timetable'), ('exam', 'Exam'), ('gradebook', 'Gradebook'), ('assignment', 'Assignment'), ('submission', 'Submission'), ('template', 'Template'), ('email', 'Email'), ('sms', 'SMS'), ('log', 'Communication Log'), ('dashboard', 'Dashboard'), ('report', 'Report'), ('user_management', 'User Management'), ('role_management', 'Role Management'), ('school_management', 'School Management')], max_length=30)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['resource_type', 'permission_type'],
                'unique_together': {('permission_type', 'resource_type')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('super_admin', 'Super Admin'), ('school_admin', 'School Admin'), ('teacher', 'Teacher'), ('accountant', 'Accountant'), ('parent', 'Parent'), ('student', 'Student')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this role')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='core.permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='core.role'),
        ),
    ]
