# Generated by Django 5.2.3 on 2026-01-23 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_allow_same_subject_across_learning_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this role belongs to. Leave blank for system-wide roles (not recommended).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.school'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Role name (use lowercase with underscores, e.g., "librarian", "security_guard")', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('school', 'name')},
        ),
    ]
