# Generated by Django 5.2.3 on 2025-11-24 05:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_userprofile_role_permission_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('charge', models.DecimalField(decimal_places=2, help_text='Charge per term for this activity', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_mandatory', models.BooleanField(default=False, help_text='If checked, all students will be automatically assigned this activity unless they have an exception')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.school')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['is_mandatory', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
    ]
