# Generated by Django 5.2.3 on 2025-12-24 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_student_options_alter_student_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='activity',
            name='school',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['grade', 'first_name', 'last_name']},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'student_id')},
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(blank=True, help_text='Assigned class (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.schoolclass'),
        ),
        migrations.DeleteModel(
            name='ActivityException',
        ),
        migrations.RemoveField(
            model_name='student',
            name='activities',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
