# Generated by Django 5.2.3 on 2025-12-25 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_activity_unique_together_and_more'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='Assigned class teacher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_taught', to='timetable.teacher'),
        ),
    ]
