# Generated by Django 5.2.3 on 2025-12-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_schoolclass_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='primary_color',
            field=models.CharField(default='#0d6efd', help_text='Primary color for the school theme (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='school',
            name='use_color_scheme',
            field=models.BooleanField(default=False, help_text='Apply this color scheme to the application'),
        ),
    ]
