# Generated by Django 5.2.3 on 2025-12-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_school_color_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='secondary_color',
            field=models.CharField(blank=True, help_text='Secondary color for the school theme (hex code)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='use_secondary_on_headers',
            field=models.BooleanField(default=False, help_text='Apply secondary color to headers'),
        ),
    ]
