# Generated by Django 5.2.3 on 2025-12-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_secondary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportroute',
            name='active_end_date',
            field=models.DateField(blank=True, help_text='End date when this route becomes inactive', null=True),
        ),
        migrations.AddField(
            model_name='transportroute',
            name='active_start_date',
            field=models.DateField(blank=True, help_text='Start date when this route becomes active', null=True),
        ),
    ]
