# Generated by Django 5.2.3 on 2025-12-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_transport_route_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecategory',
            name='apply_by_default',
            field=models.BooleanField(default=False, help_text='If checked, optional fees will be selected by default when adding/editing students'),
        ),
        migrations.AddField(
            model_name='student',
            name='optional_fee_categories',
            field=models.ManyToManyField(blank=True, help_text='Optional fee categories this student has opted into', related_name='students_opted_in', to='core.feecategory'),
        ),
        migrations.AlterField(
            model_name='feecategory',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='If checked, this fee is optional and students can opt in/out'),
        ),
    ]
