# Generated by Django 5.2.3 on 2025-12-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_optional_fee_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['grade', 'first_name', 'middle_name', 'last_name']},
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Middle or other names (optional)', max_length=100),
        ),
    ]
