# Generated by Django 5.2.3 on 2025-12-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_middle_name_to_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='upi',
            field=models.CharField(blank=True, help_text='11-digit NEMIS / UPI number issued by the Ministry of Education', max_length=11, null=True, unique=True, verbose_name='NEMIS/UPI Number'),
        ),
    ]
