# Generated by Django 5.2.3 on 2025-12-29 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_student_upi_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "2023-2024"', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False, help_text='Whether this academic year is currently active')),
                ('is_current', models.BooleanField(default=False, help_text='The current academic year (only one can be current)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='core.school')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_date'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PromotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('bulk', 'Bulk')], default='automatic', max_length=20)),
                ('total_students', models.PositiveIntegerField(help_text='Total students processed')),
                ('promoted_count', models.PositiveIntegerField(default=0)),
                ('retained_count', models.PositiveIntegerField(default=0)),
                ('graduated_count', models.PositiveIntegerField(default=0)),
                ('left_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this promotion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='core.academicyear')),
                ('promoted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_logs', to='core.school')),
                ('to_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='core.academicyear')),
            ],
            options={
                'verbose_name': 'Promotion Log',
                'verbose_name_plural': 'Promotion Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "A", "B", "Morning", "Afternoon"', max_length=50)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of students (optional)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.schoolclass')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['school_class__grade__name', 'school_class__name', 'name'],
                'unique_together': {('school_class', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudentClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.PositiveIntegerField(blank=True, help_text='Roll number in class', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retained', 'Retained'), ('promoted', 'Promoted'), ('graduated', 'Graduated'), ('left', 'Left School'), ('dropped', 'Dropped Out')], default='active', max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this enrollment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.academicyear')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.grade')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='core.schoolclass')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='core.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student')),
            ],
            options={
                'verbose_name': 'Student Class Enrollment',
                'verbose_name_plural': 'Student Class Enrollments',
                'ordering': ['roll_number', 'student__first_name', 'student__last_name'],
                'indexes': [models.Index(fields=['academic_year', 'status'], name='core_studen_academi_e5c0af_idx'), models.Index(fields=['grade', 'academic_year'], name='core_studen_grade_i_e842f1_idx'), models.Index(fields=['school_class', 'section'], name='core_studen_school__d667fc_idx')],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
