# Generated by Django 5.2.3 on 2025-11-21 08:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_userprofile_created_at_and_more'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Weight percentage for this exam type', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='core.school')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('passing_marks', models.DecimalField(decimal_places=2, default=40, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='timetable.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.term')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.examtype')),
            ],
            options={
                'ordering': ['-exam_date', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='Gradebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='exams.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='core.student')),
            ],
            options={
                'ordering': ['student', 'exam'],
            },
        ),
        migrations.CreateModel(
            name='GradebookSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('average_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_grade', models.CharField(blank=True, max_length=5)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_summaries', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_summaries', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_summaries', to='timetable.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_summaries', to='core.term')),
            ],
            options={
                'ordering': ['student', 'term', 'subject'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['term', 'subject'], name='exams_exam_term_id_3fa7a7_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_date'], name='exams_exam_exam_da_1bca11_idx'),
        ),
        migrations.AddIndex(
            model_name='gradebook',
            index=models.Index(fields=['student', 'exam'], name='exams_grade_student_21a352_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradebook',
            unique_together={('school', 'student', 'exam')},
        ),
        migrations.AlterUniqueTogether(
            name='gradebooksummary',
            unique_together={('school', 'student', 'term', 'subject')},
        ),
    ]
