# Generated by Django 5.2.3 on 2026-01-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_performance_indexes'),
        ('exams', '0001_initial'),
        ('timetable', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examtype',
            index=models.Index(fields=['school', 'is_active'], name='examtype_school_active_idx'),
        ),
        migrations.AddIndex(
            model_name='gradebooksummary',
            index=models.Index(fields=['school', 'student', 'term'], name='gb_sum_sch_stu_term_idx'),
        ),
        migrations.AddIndex(
            model_name='gradebooksummary',
            index=models.Index(fields=['student', 'term', 'subject'], name='gb_sum_stu_term_sub_idx'),
        ),
        migrations.AddIndex(
            model_name='gradebooksummary',
            index=models.Index(fields=['term', 'subject'], name='gb_sum_term_sub_idx'),
        ),
    ]
