# Generated by Django 5.2.3 on 2026-01-25 12:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('stem', 'STEM (Science, Technology, Engineering, Mathematics)'), ('social_sciences', 'Social Sciences'), ('arts_sports', 'Arts & Sports')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_pathways', to='core.school')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, help_text='Internal subject code (e.g., MATH, ENG)', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('learning_level', models.CharField(blank=True, choices=[('early_years', 'Early Years (Pre-Primary 1-2)'), ('lower_primary', 'Lower Primary (Grade 1-3)'), ('upper_primary', 'Upper Primary (Grade 4-6)'), ('junior_secondary', 'Junior Secondary (Grade 7-9)')], help_text='CBC learning level this subject applies to', max_length=20, null=True)),
                ('knec_code', models.CharField(blank=True, help_text='Official KNEC subject code (e.g., 101 for Mathematics)', max_length=20, null=True)),
                ('is_compulsory', models.BooleanField(default=True, help_text='Whether this subject is compulsory or optional')),
                ('is_religious_education', models.BooleanField(default=False, help_text='Whether this is a religious education subject')),
                ('religious_type', models.CharField(blank=True, choices=[('CRE', 'Christian Religious Education'), ('IRE', 'Islamic Religious Education'), ('HRE', 'Hindu Religious Education')], help_text='Type of religious education (only if is_religious_education=True)', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_grades', models.ManyToManyField(blank=True, help_text='Grades this subject applies to', related_name='subjects', to='core.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.school')),
                ('pathway', models.ForeignKey(blank=True, help_text='Subject pathway (optional, for Junior Secondary)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='timetable.subjectpathway')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('specialization', models.CharField(blank=True, help_text='Subject specialization or area of expertise', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.school')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='timetable.subject')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('period_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('is_break', models.BooleanField(default=False)),
                ('break_name', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='core.school')),
            ],
            options={
                'ordering': ['day', 'period_number'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='core.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='timetable.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetables', to='timetable.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='timetable.timeslot')),
            ],
            options={
                'ordering': ['school_class', 'time_slot__day', 'time_slot__period_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject_selections', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_selections', to='core.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject_selections', to='core.term')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='timetable.subject')),
            ],
            options={
                'ordering': ['student', 'term', 'subject'],
                'indexes': [models.Index(fields=['student', 'term'], name='student_term_idx'), models.Index(fields=['subject', 'term'], name='subject_term_idx')],
                'unique_together': {('school', 'student', 'term', 'subject')},
            },
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['learning_level'], name='subject_learning_level_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_compulsory'], name='subject_is_compulsory_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_religious_education', 'religious_type'], name='subject_religious_idx'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('school', 'code'), name='unique_school_code_when_provided'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('knec_code__isnull', True), _negated=True), models.Q(('knec_code', ''), _negated=True), models.Q(('learning_level__isnull', True), _negated=True)), fields=('knec_code', 'learning_level'), name='unique_knec_code_per_learning_level'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'name', 'learning_level')},
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('school', 'employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('school', 'day', 'period_number')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('school', 'school_class', 'time_slot')},
        ),
    ]
