# Generated by Django 5.2.3 on 2026-01-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_allow_same_subject_across_learning_levels'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_knec_code_when_provided',
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'name', 'learning_level')},
        ),
        migrations.AlterField(
            model_name='subject',
            name='knec_code',
            field=models.CharField(blank=True, help_text='Official KNEC subject code (e.g., 101 for Mathematics)', max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('knec_code__isnull', True), _negated=True), models.Q(('knec_code', ''), _negated=True), models.Q(('learning_level__isnull', True), _negated=True)), fields=('knec_code', 'learning_level'), name='unique_knec_code_per_learning_level'),
        ),
    ]
