# Generated by Django 5.2.3 on 2026-01-26 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_performance_indexes'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['school', 'is_active'], name='teacher_school_active_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['employee_id'], name='teacher_employee_id_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['school', 'day'], name='timeslot_school_day_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['school', 'is_break'], name='timeslot_school_break_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['school', 'school_class', 'is_active'], name='tt_sch_cls_act_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['school', 'is_active'], name='timetable_school_active_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['school_class', 'is_active'], name='timetable_class_active_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['subject', 'is_active'], name='timetable_subject_active_idx'),
        ),
    ]
