# Generated by Django 5.2.3 on 2025-12-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_schoolclass_class_teacher'),
        ('timetable', '0002_teacher_address_teacher_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False), models.Q(('code', ''), _negated=True)), fields=('school', 'code'), name='unique_school_code_when_provided'),
        ),
    ]
