# Generated by Django 5.2.3 on 2025-12-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_schoolclass_class_teacher'),
        ('timetable', '0003_subject_unique_school_code_when_provided'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_school_code_when_provided',
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('school', 'code'), name='unique_school_code_when_provided'),
        ),
    ]
