# Generated by Django 5.2.3 on 2025-12-29 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_middle_name_to_student'),
        ('timetable', '0004_remove_subject_unique_school_code_when_provided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='applicable_grades',
            field=models.ManyToManyField(blank=True, help_text='Grades this subject applies to', related_name='subjects', to='core.grade'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_compulsory',
            field=models.BooleanField(default=True, help_text='Whether this subject is compulsory or optional'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_religious_education',
            field=models.BooleanField(default=False, help_text='Whether this is a religious education subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='knec_code',
            field=models.CharField(blank=True, help_text='Official KNEC subject code (e.g., 101 for Mathematics)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='learning_level',
            field=models.CharField(blank=True, choices=[('early_years', 'Early Years (Pre-Primary 1-2)'), ('lower_primary', 'Lower Primary (Grade 1-3)'), ('upper_primary', 'Upper Primary (Grade 4-6)'), ('junior_secondary', 'Junior Secondary (Grade 7-9)')], help_text='CBC learning level this subject applies to', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='religious_type',
            field=models.CharField(blank=True, choices=[('CRE', 'Christian Religious Education'), ('IRE', 'Islamic Religious Education'), ('HRE', 'Hindu Religious Education')], help_text='Type of religious education (only if is_religious_education=True)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, help_text='Internal subject code (e.g., MATH, ENG)', max_length=20),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10),
        ),
        migrations.CreateModel(
            name='StudentSubjectSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject_selections', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_selections', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='timetable.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject_selections', to='core.term')),
            ],
            options={
                'ordering': ['student', 'term', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='SubjectPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('stem', 'STEM (Science, Technology, Engineering, Mathematics)'), ('social_sciences', 'Social Sciences'), ('arts_sports', 'Arts & Sports')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_pathways', to='core.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='pathway',
            field=models.ForeignKey(blank=True, help_text='Subject pathway (optional, for Junior Secondary)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='timetable.subjectpathway'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['learning_level'], name='subject_learning_level_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_compulsory'], name='subject_is_compulsory_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_religious_education', 'religious_type'], name='subject_religious_idx'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('knec_code__isnull', True), _negated=True), models.Q(('knec_code', ''), _negated=True)), fields=('knec_code',), name='unique_knec_code_when_provided'),
        ),
        migrations.AddIndex(
            model_name='studentsubjectselection',
            index=models.Index(fields=['student', 'term'], name='student_term_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsubjectselection',
            index=models.Index(fields=['subject', 'term'], name='subject_term_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsubjectselection',
            unique_together={('school', 'student', 'term', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectpathway',
            unique_together={('school', 'name')},
        ),
    ]
