"""
Django settings for school_management project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-your-secret-key-here')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# ALLOWED_HOSTS configuration
# Django supports leading dot pattern (e.g., ".railway.app") to allow all subdomains
if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    # Get allowed hosts from environment
    allowed_hosts_str = config('ALLOWED_HOSTS', default='')
    if allowed_hosts_str:
        # Support both comma-separated and wildcard patterns
        hosts = []
        for host in allowed_hosts_str.split(','):
            host = host.strip().strip('"').strip("'")
            if host.startswith('*.') or host.startswith('.'):
                # Convert *.railway.app to .railway.app (Django's pattern)
                if host.startswith('*.'):
                    host = host[1:]  # Remove * but keep the dot
                hosts.append(host)
            elif host:
                hosts.append(host)
        ALLOWED_HOSTS = hosts if hosts else ['.railway.app', '.up.railway.app']
    else:
        # Fallback: allow all Railway domains using leading dot pattern
        ALLOWED_HOSTS = ['.railway.app', '.up.railway.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'corsheaders',
    'storages',  # For AWS S3 media file storage
    'widget_tweaks',
    'core',
    'payments',
    'communications',
    'attendance',
    'timetable',
    'exams',
    'homework',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.OptimizeUserProfileMiddleware',  # Optimize profile queries
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'school_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'core', 'templates'),
            os.path.join(BASE_DIR, 'payments', 'templates'),
            os.path.join(BASE_DIR, 'communications', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.user_profile_optimized',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_management.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Database configuration
# First try to use DATABASE_URL (Railway provides this automatically)
# If not available, construct from individual DB_* variables with defaults
database_url = config('DATABASE_URL', default=None)
if database_url:
    DATABASES = {
        'default': dj_database_url.config(default=database_url)
    }
else:
    # Fallback: construct from individual variables with defaults
    DATABASES = {
        'default': dj_database_url.config(
            default=f"postgresql://{config('DB_USER', default='postgres')}:{config('DB_PASSWORD', default='postgres')}@{config('DB_HOST', default='localhost')}:{config('DB_PORT', default='5432')}/{config('DB_NAME', default='school_mgt_db_dev')}"
        )
    }

SECRET_KEY = config('SECRET_KEY')

# Database configuration - Railway provides DATABASE_URL automatically
"""DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default='sqlite:///db.sqlite3')
    )
}"""

# CSRF trusted origins - CSRF_TRUSTED_ORIGINS doesn't support wildcards, needs exact domains
csrf_origins = config('CSRF_TRUSTED_ORIGINS', default='')
if csrf_origins:
    origins = []
    for origin in csrf_origins.split(','):
        origin = origin.strip().strip('"').strip("'")
        # Remove wildcard patterns - CSRF doesn't support them
        if origin.startswith('https://*.'):
            # Can't use wildcards in CSRF_TRUSTED_ORIGINS, user needs to set specific domain
            continue
        elif origin and origin.startswith('http'):
            origins.append(origin)
    CSRF_TRUSTED_ORIGINS = origins if origins else []
else:
    # Try to get Railway domain automatically and add https://
    railway_domain = config('RAILWAY_PUBLIC_DOMAIN', default='')
    if railway_domain:
        # Ensure it starts with https://
        if not railway_domain.startswith('http'):
            CSRF_TRUSTED_ORIGINS = [f'https://{railway_domain}']
        else:
            CSRF_TRUSTED_ORIGINS = [railway_domain]
    else:
        # Fallback: empty list (will need to be set manually with actual domain)
        CSRF_TRUSTED_ORIGINS = []

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'  # English

TIME_ZONE = 'UTC'  # Coordinated Universal Time

USE_I18N = True

USE_TZ = True

# Date format for Indian market (dd-mm-yyyy)
DATE_FORMAT = 'd-m-Y'
DATETIME_FORMAT = 'd-m-Y H:i'
SHORT_DATE_FORMAT = 'd-m-Y'
SHORT_DATETIME_FORMAT = 'd-m-Y H:i'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Static files directories - create if they don't exist
static_dirs = [os.path.join(BASE_DIR, 'static')]
STATICFILES_DIRS = [d for d in static_dirs if os.path.exists(d)]

# Media files (User uploaded files)
# Use AWS S3 for production, local storage for development

# S3 Storage Configuration
# Check USE_S3 environment variable - handle various formats (True, "True", true, 1, etc.)
use_s3_raw = config('USE_S3', default='False')
# Normalize the value - handle string "True"/"False", boolean, or numeric
# Remove quotes if present (Railway might set it as "True")
if isinstance(use_s3_raw, str):
    # Strip whitespace and quotes (both single and double)
    use_s3_clean = use_s3_raw.strip().strip('"').strip("'").lower()
    USE_S3 = use_s3_clean in ('true', '1', 'yes', 'on')
else:
    USE_S3 = bool(use_s3_raw)

if USE_S3:
    if "storages" not in INSTALLED_APPS:
        INSTALLED_APPS.append("storages")

    AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID", default='')
    AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY", default='')
    AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME", default='')

    AWS_S3_ENDPOINT_URL = config("AWS_S3_ENDPOINT_URL", default='')
    # Railway may provide "auto" as region - convert to valid region code if needed
    region = config('AWS_S3_REGION_NAME', default='us-east-1')
    if isinstance(region, str) and region.lower() == 'auto':
        region = 'us-east-1'  # Default fallback for Railway's "auto" region
    AWS_S3_REGION_NAME = region

    AWS_DEFAULT_ACL = "public-read"
    AWS_QUERYSTRING_AUTH = False

    AWS_S3_FILE_OVERWRITE = False

    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",
    }

    # Django 5.2+ uses STORAGES setting (DEFAULT_FILE_STORAGE was removed in 5.1)
    STORAGES = {
        'default': {
            'BACKEND': 'core.storage_backends.RailwayStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

    # Explicitly unset MEDIA_URL and MEDIA_ROOT when using S3
    # Django will use the storage backend's url() method instead
    MEDIA_URL = None
    MEDIA_ROOT = None

else:
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    # Django 5.2+ uses STORAGES setting
    # When not using S3, Django defaults to FileSystemStorage, but we can be explicit
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'core:home'  # Redirect to home page after login
LOGOUT_REDIRECT_URL = 'login'  # Redirect to login after logout

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins in development
if not DEBUG:
    CORS_ALLOWED_ORIGINS = [
        # Add your production domain here
        # "https://yourdomain.com",
    ]

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)

# Celcom Africa settings for SMS
CELCOM_URL_SENDSMS = config('CELCOM_URL_SENDSMS', default='')
CELCOM_URL_GETBALANCE = config('CELCOM_URL_GETBALANCE', default='')
CELCOM_API_KEY = config('CELCOM_API_KEY', default='')
CELCOM_PARTNER_ID = config('CELCOM_PARTNER_ID', default='')
CELCOM_SHORTCODE = config('CELCOM_SHORTCODE', default='')
CELCOM_COMPANY_PHONE = config('CELCOM_COMPANY_PHONE', default='')

# M-Pesa settings
MPESA_CONSUMER_KEY = config('MPESA_CONSUMER_KEY', default='')
MPESA_CONSUMER_SECRET = config('MPESA_CONSUMER_SECRET', default='')
MPESA_BUSINESS_SHORT_CODE = config('MPESA_BUSINESS_SHORT_CODE', default='')
MPESA_PASSKEY = config('MPESA_PASSKEY', default='')
MPESA_ENVIRONMENT = config('MPESA_ENVIRONMENT', default='sandbox')  # sandbox or live

# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 3600  # 1 hour in seconds
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SECURE = True  # for HTTPS
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access

# Security middleware settings
SECURE_SSL_REDIRECT = not DEBUG  # Redirect all HTTP traffic to HTTPS only in production
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Additional security headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking
REFERRER_POLICY = 'same-origin'

# Message tags for Bootstrap alert styling
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'info',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# M-Pesa API Settings
MPESA_CONSUMER_KEY = config('MPESA_CONSUMER_KEY', default='')
MPESA_CONSUMER_SECRET = config('MPESA_CONSUMER_SECRET', default='')
MPESA_PASSKEY = config('MPESA_PASSKEY', default='')
MPESA_SHORTCODE = config('MPESA_SHORTCODE', default='')
MPESA_CALLBACK_URL = config('MPESA_CALLBACK_URL', default='https://your-domain.com/core/api/mpesa/callback/')
MPESA_ENVIRONMENT = config('MPESA_ENVIRONMENT', default='sandbox')  # 'sandbox' or 'production'