# Generated by Django 5.2.3 on 2026-01-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancesummary',
            index=models.Index(fields=['school', 'student', 'term'], name='att_sum_sch_stu_term_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesummary',
            index=models.Index(fields=['student', 'term'], name='att_sum_stu_term_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesummary',
            index=models.Index(fields=['term'], name='att_sum_term_idx'),
        ),
    ]
