# Generated by Django 5.2.3 on 2026-01-25 12:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='Name of the bank (e.g., Equity Bank, KCB, etc.)', max_length=100)),
                ('pattern_name', models.CharField(help_text='Descriptive name for this pattern', max_length=100)),
                ('date_column', models.CharField(help_text='Column name or index for transaction date (e.g., "Date", "Transaction Date", "0")', max_length=50)),
                ('amount_column', models.CharField(help_text='Column name or index for amount (e.g., "Amount", "Debit", "Credit", "1")', max_length=50)),
                ('reference_column', models.CharField(help_text='Column name or index for narrative/reference containing M-Pesa details (e.g., "Narrative", "Description", "2")', max_length=50)),
                ('transaction_reference_column', models.CharField(blank=True, help_text='Column name or index for unique bank transaction reference number (e.g., "Transaction Ref", "Reference", "3") - used for duplicate detection', max_length=50)),
                ('student_id_pattern', models.CharField(blank=True, help_text='Regex pattern to extract student ID from reference (e.g., r"STUDENT\\s*(\\d+)" or r"(\\d{5})" or r"#(\\d+)" for M-Pesa format BUSINESS#STUDENT_ID)', max_length=200)),
                ('amount_pattern', models.CharField(blank=True, help_text='Regex pattern to extract amount if needed (optional)', max_length=200)),
                ('date_format', models.CharField(default='%Y-%m-%d', help_text='Date format in Python strftime format (e.g., "%Y-%m-%d", "%d/%m/%Y", "%m/%d/%Y")', max_length=50)),
                ('has_header', models.BooleanField(default=True, help_text='Whether CSV file has header row')),
                ('delimiter', models.CharField(default=',', help_text='CSV delimiter (comma, semicolon, tab)', max_length=5)),
                ('encoding', models.CharField(default='utf-8', help_text='File encoding (utf-8, latin-1, etc.)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statement_patterns', to='core.school')),
            ],
            options={
                'ordering': ['school', 'bank_name', 'pattern_name'],
                'unique_together': {('school', 'bank_name', 'pattern_name')},
            },
        ),
        migrations.CreateModel(
            name='BankStatementUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_transactions', models.IntegerField(default=0)),
                ('matched_payments', models.IntegerField(default=0)),
                ('unmatched_payments', models.IntegerField(default=0)),
                ('duplicate_transactions', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='receivables.bankstatementpattern')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statement_uploads', to='core.school')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.student')),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.studentfee')),
            ],
            options={
                'ordering': ['-payment_date'],
                'unique_together': {('school', 'payment_id')},
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(choices=[('overpayment', 'Overpayment'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('reassignment', 'Payment Reassignment'), ('other', 'Other')], default='overpayment', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_applied', models.BooleanField(default=False, help_text='Whether this credit has been applied to fees')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_to_fee', models.ForeignKey(blank=True, help_text='Fee this credit was applied to (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_credits', to='core.studentfee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='core.student')),
                ('payment', models.ForeignKey(blank=True, help_text='Payment that created this credit (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='receivables.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('result_code', models.CharField(blank=True, max_length=10)),
                ('result_desc', models.TextField(blank=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_payments', to='core.school')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_details', to='receivables.payment')),
            ],
            options={
                'verbose_name': 'M-Pesa Payment',
                'verbose_name_plural': 'M-Pesa Payments',
                'unique_together': {('school', 'payment')},
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='receivables.payment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='core.school')),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='core.studentfee')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('school', 'payment', 'student_fee')},
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=20)),
                ('fee_category', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=9)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='receivables.payment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.student')),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('school', 'receipt_number')},
            },
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('due_date', 'Due Date Reminder'), ('overdue', 'Overdue Payment'), ('partial', 'Partial Payment'), ('receipt', 'Payment Receipt')], max_length=20)),
                ('message', models.TextField()),
                ('sent_via_email', models.BooleanField(default=False)),
                ('sent_via_sms', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.student')),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.studentfee')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('school', 'student', 'student_fee', 'reminder_type', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_date', models.DateField()),
                ('is_cleared', models.BooleanField(default=False)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='core.student')),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='core.studentfee')),
            ],
            options={
                'ordering': ['due_date', 'student'],
                'unique_together': {('school', 'student_fee')},
            },
        ),
        migrations.CreateModel(
            name='UnmatchedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference/narrative from bank statement', max_length=200)),
                ('bank_reference_number', models.CharField(blank=True, db_index=True, help_text='Unique bank transaction reference number (for duplicate detection per school)', max_length=100, null=True)),
                ('mpesa_reference', models.CharField(blank=True, db_index=True, help_text='M-Pesa transaction reference (e.g., TK18K8USG7) - unique identifier', max_length=50, null=True)),
                ('mobile_number', models.CharField(blank=True, help_text='Mobile number from M-Pesa narrative (e.g., 254721266013)', max_length=15, null=True)),
                ('extracted_student_id', models.CharField(blank=True, help_text='Student ID extracted from reference (if any)', max_length=50, null=True)),
                ('bank_account', models.CharField(blank=True, help_text='Bank account number if available', max_length=100)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit (Deposit)'), ('debit', 'Debit (Withdrawal)')], default='credit', max_length=20)),
                ('status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('ignored', 'Ignored'), ('manual', 'Manual Match')], default='unmatched', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this transaction')),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_transactions', to=settings.AUTH_USER_MODEL)),
                ('matched_payment', models.ForeignKey(blank=True, help_text='Payment this transaction was matched to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_transactions', to='receivables.payment')),
                ('matched_student', models.ForeignKey(blank=True, help_text='Student this transaction was matched to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmatched_transactions', to='core.student')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unmatched_transactions', to='core.school')),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unmatched_transactions', to='receivables.bankstatementupload')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['school', 'status', 'transaction_date'], name='receivables_school__19a7ab_idx'), models.Index(fields=['school', 'extracted_student_id'], name='receivables_school__50c05d_idx'), models.Index(fields=['school', 'bank_reference_number'], name='unmatched_bank_ref_idx'), models.Index(fields=['school', 'mpesa_reference'], name='unmatched_mpesa_ref_idx')],
                'unique_together': {('school', 'bank_reference_number')},
            },
        ),
    ]
