# Generated by Django 5.2.3 on 2026-01-25 07:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_school_to_role'),
        ('receivables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_details', to='receivables.payment'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='receivables.payment'),
        ),
        migrations.CreateModel(
            name='BankStatementPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='Name of the bank (e.g., Equity Bank, KCB, etc.)', max_length=100)),
                ('pattern_name', models.CharField(help_text='Descriptive name for this pattern', max_length=100)),
                ('date_column', models.CharField(help_text='Column name or index for transaction date (e.g., "Date", "Transaction Date", "0")', max_length=50)),
                ('amount_column', models.CharField(help_text='Column name or index for amount (e.g., "Amount", "Debit", "Credit", "1")', max_length=50)),
                ('reference_column', models.CharField(blank=True, help_text='Column name or index for reference/narrative (e.g., "Narrative", "Description", "2")', max_length=50)),
                ('student_id_pattern', models.CharField(blank=True, help_text='Regex pattern to extract student ID from reference (e.g., r"STUDENT\\s*(\\d+)" or r"(\\d{5})")', max_length=200)),
                ('amount_pattern', models.CharField(blank=True, help_text='Regex pattern to extract amount if needed (optional)', max_length=200)),
                ('date_format', models.CharField(default='%Y-%m-%d', help_text='Date format in Python strftime format (e.g., "%Y-%m-%d", "%d/%m/%Y", "%m/%d/%Y")', max_length=50)),
                ('has_header', models.BooleanField(default=True, help_text='Whether CSV file has header row')),
                ('delimiter', models.CharField(default=',', help_text='CSV delimiter (comma, semicolon, tab)', max_length=5)),
                ('encoding', models.CharField(default='utf-8', help_text='File encoding (utf-8, latin-1, etc.)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statement_patterns', to='core.school')),
            ],
            options={
                'ordering': ['school', 'bank_name', 'pattern_name'],
                'unique_together': {('school', 'bank_name', 'pattern_name')},
            },
        ),
        migrations.CreateModel(
            name='BankStatementUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_transactions', models.IntegerField(default=0)),
                ('matched_payments', models.IntegerField(default=0)),
                ('unmatched_payments', models.IntegerField(default=0)),
                ('duplicate_transactions', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='receivables.bankstatementpattern')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statement_uploads', to='core.school')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(choices=[('overpayment', 'Overpayment'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('reassignment', 'Payment Reassignment'), ('other', 'Other')], default='overpayment', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_applied', models.BooleanField(default=False, help_text='Whether this credit has been applied to fees')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_to_fee', models.ForeignKey(blank=True, help_text='Fee this credit was applied to (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_credits', to='core.studentfee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, help_text='Payment that created this credit (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='receivables.payment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='receivables.payment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='core.school')),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='core.studentfee')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('school', 'payment', 'student_fee')},
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_date', models.DateField()),
                ('is_cleared', models.BooleanField(default=False)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='core.student')),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='core.studentfee')),
            ],
            options={
                'ordering': ['due_date', 'student'],
                'unique_together': {('school', 'student_fee')},
            },
        ),
    ]
