# Generated by Django 5.2.3 on 2026-01-26 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_performance_indexes'),
        ('receivables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['school', 'student', 'is_applied'], name='credit_sch_stu_app_idx'),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['student', 'is_applied'], name='credit_student_applied_idx'),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['is_applied'], name='credit_is_applied_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['school', 'student', 'payment_date'], name='pay_sch_stu_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['school', 'status', 'payment_date'], name='payment_school_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'payment_date'], name='payment_student_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['payment', 'student_fee'], name='pay_alloc_pay_fee_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['student_fee'], name='pay_alloc_stu_fee_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['school', 'student', 'issued_at'], name='pay_receipt_sch_stu_iss_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['student', 'issued_at'], name='pay_receipt_stu_iss_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['issued_at'], name='paymentreceipt_issued_at_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreminder',
            index=models.Index(fields=['school', 'student', 'created_at'], name='pay_remind_sch_stu_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreminder',
            index=models.Index(fields=['student', 'created_at'], name='pay_remind_stu_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreminder',
            index=models.Index(fields=['reminder_type', 'created_at'], name='pay_remind_type_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['school', 'student', 'is_cleared'], name='receiv_sch_stu_clr_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['school', 'due_date', 'is_cleared'], name='receiv_sch_due_clr_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['student', 'is_cleared'], name='receivable_student_cleared_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['due_date'], name='receivable_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['is_cleared'], name='receivable_is_cleared_idx'),
        ),
    ]
