# Generated by Django 5.2.3 on 2026-01-25 07:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_school_to_role'),
        ('receivables', '0002_alter_mpesapayment_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatementpattern',
            name='student_id_pattern',
            field=models.CharField(blank=True, help_text='Regex pattern to extract student ID from reference (e.g., r"STUDENT\\s*(\\d+)" or r"(\\d{5})" or r"#(\\d+)" for M-Pesa format BUSINESS#STUDENT_ID)', max_length=200),
        ),
        migrations.CreateModel(
            name='UnmatchedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference/narrative from bank statement', max_length=200)),
                ('extracted_student_id', models.CharField(blank=True, help_text='Student ID extracted from reference (if any)', max_length=50, null=True)),
                ('bank_account', models.CharField(blank=True, help_text='Bank account number if available', max_length=100)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit (Deposit)'), ('debit', 'Debit (Withdrawal)')], default='credit', max_length=20)),
                ('status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('ignored', 'Ignored'), ('manual', 'Manual Match')], default='unmatched', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this transaction')),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_transactions', to=settings.AUTH_USER_MODEL)),
                ('matched_payment', models.ForeignKey(blank=True, help_text='Payment this transaction was matched to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_transactions', to='receivables.payment')),
                ('matched_student', models.ForeignKey(blank=True, help_text='Student this transaction was matched to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmatched_transactions', to='core.student')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unmatched_transactions', to='core.school')),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unmatched_transactions', to='receivables.bankstatementupload')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['school', 'status', 'transaction_date'], name='receivables_school__19a7ab_idx'), models.Index(fields=['school', 'extracted_student_id'], name='receivables_school__50c05d_idx')],
            },
        ),
    ]
