# Generated by Django 5.2.3 on 2026-01-25 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_school_to_role'),
        ('receivables', '0003_alter_bankstatementpattern_student_id_pattern_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unmatchedtransaction',
            name='bank_reference_number',
            field=models.CharField(blank=True, db_index=True, help_text='Unique bank transaction reference number (for duplicate detection per school)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unmatchedtransaction',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Mobile number from M-Pesa narrative (e.g., 254721266013)', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='unmatchedtransaction',
            name='mpesa_reference',
            field=models.CharField(blank=True, db_index=True, help_text='M-Pesa transaction reference (e.g., TK18K8USG7) - unique identifier', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatementpattern',
            name='reference_column',
            field=models.CharField(help_text='Column name or index for narrative/reference containing M-Pesa details (e.g., "Narrative", "Description", "2")', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='unmatchedtransaction',
            unique_together={('school', 'bank_reference_number')},
        ),
        migrations.AddIndex(
            model_name='unmatchedtransaction',
            index=models.Index(fields=['school', 'bank_reference_number'], name='unmatched_bank_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='unmatchedtransaction',
            index=models.Index(fields=['school', 'mpesa_reference'], name='unmatched_mpesa_ref_idx'),
        ),
    ]
