# Generated by Django 5.2.3 on 2026-01-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0004_unmatchedtransaction_bank_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementpattern',
            name='transaction_reference_column',
            field=models.CharField(blank=True, help_text='Column name or index for unique bank transaction reference number (e.g., "Transaction Ref", "Reference", "3") - used for duplicate detection', max_length=50),
        ),
    ]
